### PR TITLE
Set manual trigger for Chromatic workflow

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Towards the goal of testing out Chromatic (free version) on #19, setting trigger for workflow to only occur manually

### CODE REVIEW

**Review by garrettmflynn — APPROVED** [review]
Looks good to me! Let me know when you've got an instance running, I'd love to see how it feels to interact with the Chromatic UI

**Comment by CodyCBakerPhD** [comment]
> Let me know when you've got an instance running, I'd love to see how it feels to interact with the Chromatic UI

Ahhh I was going to ask if you could handle trying to get that setup 😆 I don't think I have the time right now, plus would be good experience for you to learn how that GitHub action works

**Comment by CodyCBakerPhD** [comment]
The action will for sure need to set a secret variable or two, so if you aren't able to control that just send the tokens to me over a secure line and I'll add them as soon as I can

**Comment by garrettmflynn** [comment]
Okay yeah, I was gonna do that originally—but I don't have the required permissions in this repo to access the Settings tab.

**Comment by garrettmflynn** [comment]
Just to note, Chromatic cannot test #19 as those elements are not components in Storybook. I've created #26 to install Chromatic and have manually tested this installation with a change to the multi-select form component.

**Pull request merged**
