### PR TITLE
Added basic API tests to the new Flask endpoint for neuroconv

### PR DESCRIPTION
**Pull request by garrettmflynn**
Implemented basic tests for the Flask endpoint in pytest after talking with @CodyCBakerPhD about the implementation and PR process.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn This PR looks great except for the source-schema related tests; can you redo this PR branching from main? (a rebase of that last commit might also work too, not sure)

**Comment by garrettmflynn** [comment]
That new PR is now live at #12. Similar to #2, we can likely just convert this to a Draft PR for the sake of maintaining the changelog.

**Comment by CodyCBakerPhD** [comment]
#2 still has some unique content for reference I think, but can this one be closed?

**Comment by garrettmflynn** [comment]
Yep! Closing now.

**Pull request closed without merging**
